version: 2
jobs:
  build:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
        enviroment:
          APP_ENV: test
          DATABASE_URL: mysql://root@127.0.0.1/circle_test
          MAILER_FROM: micro@micropost.com
          MAILER_URL: smtp://7446ba11e59b8d:7b6a19a40c2a75@smtp.mailtrap.io:25
      - image: circleci/mysql:5.7
        enviroment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circle_test
    steps:
      - checkout
      - run:
          name: Install PHP libzip-dev
          command: sudo apt-get install -y libzip-dev
      - run:
          name: Install PHP & My_SQL
          command: sudo docker-php-ext-install pdo_mysql pdo mbstring zip
      - run:
          name: Wait for My_SQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Composer Update
          command: sudo composer self-update
      - run:
          name: Composer install dependancies
          command: composer install -n --prefer-dist
      - run:
          name: Run migrations
          command: php bin/console doctrine:migrations:migrate --env=test --no-interaction
      - run:
          name: Run Test
          command: ./bin/phpunit
  deploy:
    working_directory: ~/micropost
    docker:
      - image: circleci/php:7.2.4-apache-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Install PHP libzip-dev
          command: sudo apt-get install -y libzip-dev
      - run:
          name: Install PHP & My_SQL
          command: sudo docker-php-ext-install pdo_mysql pdo mbstring zip
      - run:
          name: Composer Install
          command: composer install -n --prefer-dist
      - run:
          name: Clear Cache
          command: php bin/console cache:clear --env=prod --no-interaction
      - run:
          name: Install Uglify
          command: npm i -D uglifyjs-webpack-plugin
      - run:
          name: Yarn
          command: yarn install && yarn run encore production
      - run:
          name: Add droplet
          command: ssh-keyscan -H $DROPLET_IP >> ~/.ssh/known_hosts
      - run:
          name: Pre-deploy
          command: ssh -T $DROPLET_USER:$DROPLET_IP < bin/deploy/pre_deploy.sh
      - run:
          name: Deploy code
          command: rsync -vzcrSLhp --exclude '.env' --delete ~/micropost/ $DROPLET_USER@$DROPLET_IP:/var/wwww/micropost_current
      - run:
          name: Post deploy
          command: ssh -T $DROPLET_USER:$DROPLET_IP < bin/deploy/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master